# Generated by Django 4.1.4 on 2022-12-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='social',
            name='us',
        ),
        migrations.DeleteModel(
            name='SubscribeEmail',
        ),
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
