# Generated by Django 4.1.4 on 2022-12-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_aboutus_created_at_alter_aboutus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
