# Generated by Django 4.1.4 on 2022-12-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_contactus_is_billing_contactus_is_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='is_billing',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='is_shipping',
        ),
    ]
