# Generated by Django 4.1.4 on 2022-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='discount',
            field=models.ManyToManyField(blank=True, to='Product.discount'),
        ),
    ]
