# Generated by Django 4.1.4 on 2022-12-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_basketitem_basket_remove_basketitem_version_and_more'),
        ('Product', '0003_brand_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productversiondetail',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productversiondetail',
            name='version',
        ),
        migrations.RemoveField(
            model_name='versionimage',
            name='version',
        ),
        migrations.RemoveField(
            model_name='versionreview',
            name='version',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductVersion',
        ),
        migrations.DeleteModel(
            name='ProductVersionDetail',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='VersionImage',
        ),
        migrations.DeleteModel(
            name='VersionReview',
        ),
    ]
