# Generated by Django 4.1.4 on 2023-01-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_alter_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productversiondetail",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="Product.size",
            ),
        ),
    ]
