# Generated by Django 4.1.4 on 2022-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionreview',
            name='price',
            field=models.PositiveIntegerField(choices=[('1', '20'), ('2', '40'), ('3', '60'), ('4', '80'), ('5', '100')], default=0),
        ),
        migrations.AlterField(
            model_name='versionreview',
            name='quality',
            field=models.PositiveIntegerField(choices=[('1', '20'), ('2', '40'), ('3', '60'), ('4', '80'), ('5', '100')], default=0),
        ),
        migrations.AlterField(
            model_name='versionreview',
            name='value',
            field=models.PositiveIntegerField(choices=[('1', '20'), ('2', '40'), ('3', '60'), ('4', '80'), ('5', '100')], default=0),
        ),
    ]
