# Generated by Django 4.1.4 on 2023-01-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0006_alter_productversion_sell_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productversion",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
