# Generated by Django 4.1.4 on 2023-01-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_productversion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='raiting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
