# Generated by Django 4.1.4 on 2023-01-11 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0012_rename_image_url_versionimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionreview',
            name='email',
        ),
        migrations.RemoveField(
            model_name='versionreview',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='versionreview',
            name='last_name',
        ),
        migrations.AddField(
            model_name='versionreview',
            name='summary',
            field=models.CharField(blank=True, default='summary', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='versionreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
