# Generated by Django 4.1.4 on 2023-01-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_versionreview_avarege_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versionreview',
            old_name='description',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='versionreview',
            name='summary',
            field=models.CharField(max_length=64),
        ),
    ]
