# Generated by Django 4.1.4 on 2023-01-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Product",
            "0016_product_description_alter_versionreview_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
