# Generated by Django 4.1.4 on 2022-12-30 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0003_alter_blogcomment_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
