# Generated by Django 4.1.4 on 2023-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0009_alter_blog_category"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(fields=["header"], name="Blog_blog_header_136e83_idx"),
        ),
        migrations.AddIndex(
            model_name="blogcategory",
            index=models.Index(fields=["name"], name="Blog_blogca_name_98f07c_idx"),
        ),
    ]
