# Generated by Django 4.1.4 on 2023-01-30 15:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0010_blog_blog_blog_header_136e83_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="description_az",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="description_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="header_az",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="header_en",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="name_az",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="name_en",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="comment_az",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="comment_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="name_az",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="blogcomment",
            name="name_en",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
