# Generated by Django 4.1.4 on 2023-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0011_blog_description_az_blog_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
