# Generated by Django 4.1.4 on 2023-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0014_alter_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default/admin-photo.jpg",
                null=True,
                upload_to="media/images/blogs",
            ),
        ),
    ]
