# Generated by Django 4.1.4 on 2023-02-01 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0015_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogs",
                to="Blog.blogcategory",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/images/blogs"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
