# Generated by Django 4.1.4 on 2023-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsciriberEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=64)),
            ],
        ),
    ]
