# Generated by Django 4.1.4 on 2022-12-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_contactinformation_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
