# Generated by Django 4.1.4 on 2023-01-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0004_contactinformation_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsciriberemail",
            name="email",
            field=models.EmailField(max_length=64, unique=True),
        ),
    ]
