# Generated by Django 4.1.4 on 2022-12-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_contactinformation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
