# Generated by Django 4.1.4 on 2022-12-28 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0006_delete_contactinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('address1', models.CharField(max_length=64)),
                ('address2', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(choices=[('Az', 'Azerbaijan'), ('2', 'Turkey'), ('3', 'Germany'), ('4', 'USA')], default='Az', max_length=16)),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True)),
                ('default_billing_address', models.BooleanField(default=False)),
                ('default_shipping_address', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
