# Generated by Django 4.1.4 on 2023-01-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0017_remove_product_description"),
        ("Order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Order.basket",
            ),
        ),
        migrations.AlterField(
            model_name="basketitem",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Product.productversion",
            ),
        ),
    ]
