# Generated by Django 4.1.4 on 2022-12-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='version',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='version',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
