# Generated by Django 4.1.4 on 2023-01-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0017_remove_product_description"),
        ("Order", "0003_alter_basketitem_basket_alter_basketitem_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Product.size",
            ),
        ),
    ]
