# Generated by Django 4.1.4 on 2023-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0005_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
