# Generated by Django 4.1.4 on 2023-01-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0006_alter_basketitem_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="basket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="Order.basket",
            ),
        ),
    ]
