# Generated by Django 4.1.4 on 2022-12-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_billinginformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billinginformation',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='billinginformation',
            name='email',
            field=models.EmailField(max_length=32, null=True),
        ),
    ]
