# Generated by Django 4.1.4 on 2023-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0007_alter_basketitem_basket"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
    ]
