# Generated by Django 4.1.4 on 2022-12-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_rename_telephone_billinginformation_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingInformation',
        ),
    ]
